#!/bin/sh

#starts the ad hoc server
sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode ad-hoc
sudo iwconfig wlan0 key s:adhoc
sudo iwconfig wlan0 essid 'adam'
sudo ifconfig wlan0 10.0.0.1 up

#forwards the ad hoc network to the router
sudo iptables -A FORWARD -i wlan0 -o eth0 -s 10.0.0.0/24 -m state --state NEW -j ACCEPT
sudo iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A POSTROUTING -t nat -j MASQUERADE
sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
