#!/bin/sh

name=backup-$(date +%y%m%d).tgz

if [ -f /media/sdb1/$name ]
then
    if [ "$1" == "-f" ]
    then
        rm -f /media/sdb1/$name
    else
        echo Target file already exists.
        exit 1
    fi
fi

tar czf /media/sdb1/$name -C ~ Scripts -C ~/Backup Dotfiles Firefox -C ~/Documents Tips Note Sign Todo

exit 0
