#!/bin/bash

trash ~/.adobe \
	~/.cache \
	~/.dbus \
	~/.fontconfig \
	~/.gstreamer-0.10 \
	~/.macromedia \
	~/.pulse \
	~/.thumbnails \
	~/.lesshst \
	~/.pulse-cookie \
	~/.recently-used \
	~/.recently-used.xbel \
	2>/dev/null

exit 0
