#!/bin/sh

#port=
#user=
#host=
source .hostinfo

name=$(basename "$0")
lock=$(ps -A -F | grep qTfnN | grep $user'@'$host | grep -v grep | awk '{print $2}')

if [[ "$#" = "1" && "$1" = "start" ]]
then
    if [ -n "$lock" ]
    then
        echo GFW is being fucked
        exit 1
    fi
    ssh -qTfnN -D $port $user'@'$host

elif [[ "$#" = "1" && "$1" = "stop" ]]
then
    if [ -n "$lock" ]
    then
        kill -9 $lock
        exit 0
    else
        echo GFW is not being fucked
        exit 1
    fi

else
    echo "Usage: $name start | stop"
    exit 1
fi

exit 0
