#!/bin/bash

CURRENT="`uname -r | awk -F"-" '{print $1"-"$2}'`"
HEADERS=""
IMAGES=""

for RELEASE in `dpkg --get-selections | grep ^linux-image-[0-9] | awk -F "-" '{print $3"-"$4}'`
do
	LATER=$(echo -e "${CURRENT}\n${RELEASE}" | sort -Vr | head -n 1)
	if [ "$CURRENT" != "$LATER" ]
	then
		echo "Running kernel is not the latest. $CURRENT < $LATER"
		exit 1
	else
		if [ "$RELEASE" != "$CURRENT" ]
		then
			IMAGE="`dpkg --get-selections | grep ^linux-image \
				| grep "${RELEASE}" | awk '{print $1}'`"
			IMAGES="${IMAGES} $IMAGE"
			HEADER="`dpkg --get-selections | grep ^linux-headers \
				| grep "${RELEASE}" | awk '{print $1}'`"
			HEADERS="${HEADERS} $HEADER"
			MODULE="`ls -1 /lib/modules/ |grep ^${RELEASE}`"
			MODULES="${MODULES} /lib/modules/${MODULE}"
		fi
	fi
done

PACKAGES="$IMAGES $HEADERS"

if [ "$PACKAGES" = " " ]
then
	echo "No older kernel or headers packages found."
	exit 1
fi

for PACKAGE in $PACKAGES
do
	if dpkg -s $PACKAGE 2>&1 | grep -q "Status: install ok installed"
	then
		INSTALLED_PACKAGES="${INSTALLED_PACKAGES} $PACKAGE"
	fi
done

echo
echo ------------------------------------
echo "$INSTALLED_PACKAGES $MODULES"
echo ------------------------------------
echo 

read -p "Really wanna purge these packages and directories? [y/N] " REPLY

case $REPLY in
	y | Y)
		sudo apt-get purge -y $INSTALLED_PACKAGES

		sudo rm -rvf $MODULES;;
	*)
		echo "The operation is cancelled.";;
esac

exit 0
