#!/bin/bash

if [[ "$1" =~ "-v" ]]
then
	read -p "Which key? " SALT
else
	read -s -p "Which key? " SALT
	echo
fi

if [[ "$1" =~ "-vv" ]]
then
	echo -n "$SALT" |sha512sum |cut -c 1-32 |tee >(xsel -i -p -l /dev/null)
else
	echo -n "$SALT" |sha512sum |cut -c 1-32 |xsel -i -p -l /dev/null
fi

exit 0
