#!/bin/bash

NUM=1
SORT_CMD="ls"
NAME=$(basename "$0")
TOTAL_NUM=`ls -l |grep ^- |wc -l`
LENGTH=`echo $TOTAL_NUM |awk '{print length($0)}'`

USAGE() {
	echo
	echo "Usage: $NAME [-f] [-s] [-l length]"
	echo
}

while getopts ":fl:s" arg
do
	case $arg in
		f)
			FLAG="write";;
		l)
			LENGTH_OPT="$OPTARG";;
		s)
			SORT_CMD="ls -S -r";;
		:)
			echo "Error: -$OPTARG needs an argument"
			exit 1;;
		?)
			USAGE
			exit 1;;
	esac
done

if [[ "$LENGTH_OPT" =~ ^[0-9]+$ ]]
then
	if [ "$LENGTH_OPT" -gt "$LENGTH" ]
	then
		LENGTH=$LENGTH_OPT
	fi
fi

if [ "$FLAG" = "write" ]
then
	TEMP_DIR=`mktemp -d .tmp.XXXXXXXX` || exit 1
else
	echo
	echo "Just preview, use -f to make it effective"
	echo
fi

IFS=$'\n'
for orig in `eval $SORT_CMD`
do
	if [ ! -f "$orig" ]
	then
		continue
	fi
	EXT=${orig##*.}
	echo ""`printf %0.${LENGTH}d $NUM`.$EXT"   <--   "$orig""
	if [ "$FLAG" = "write" ]
	then
		mv "$orig" "${TEMP_DIR}/`printf %0.${LENGTH}d $NUM`.$EXT"
	fi
	NUM=$[$NUM + 1]
done

if [ "$FLAG" = "write" ]
then
	mv ${TEMP_DIR}/* ./
	rmdir $TEMP_DIR
else
	USAGE
fi

exit 0
