#!/bin/bash

INTERNAL="LVDS1"
EXTERNAL=`xrandr -q |grep -v "$INTERNAL" |grep " connected" |head -n1 |cut -d' ' -f1`

[ -z $EXTERNAL ] && { xrandr --output $INTERNAL --auto; exit 0; }

if xrandr -q | grep "$INTERNAL" | grep "+" > /dev/null
then
	xrandr -q | grep "$EXTERNAL connected" > /dev/null && \
		xrandr --output $INTERNAL --off --output $EXTERNAL --auto
else
	xrandr --output $EXTERNAL --off --output $INTERNAL --auto
fi

exit 0
