#!/bin/bash

#[ -d .offlineimap/log ] || mkdir .offlineimap; touch .offlineimap/log

while true
do
	# Is offlineimap ok?
	sed '/^$/!h;$!d;g' ~/.offlineimap/log |grep -q -E "^-+$"

	if [ "$?" != "0" ]
	then
		pkill -u "$(id -u)" "offlineimap" >/dev/null 2>&1
	fi

	# Is offlineimap dead?
	pgrep -u "$(id -u)" "offlineimap" >/dev/null 2>&1

	if [ "$?" != "0" ]
	then
		cat <<- EOF >> ~/.offlineimap/log

		--------------------------------
		offlineimap started: $(date +'%Y-%m-%d %H:%M')
		--------------------------------

		EOF

		nohup offlineimap &>> ~/.offlineimap/log &
	fi

	sleep 120
done

exit 0
