#!/bin/bash

title=$1
status_string=$2
lock=/tmp/${title}-filter_lock

if [[ "$status_string" =~ "INBOX" && "$status_string" =~ "New:" ]]
then
	if [ -f "$lock" ]
	then
		printf "\ek${title}: new\e\\" > /dev/tty
	else
		notify-send "${title}: get new mails"
		printf "\ek${title}: new\e\\" > /dev/tty
		touch $lock
	fi
else
	printf "\ek${title}\e\\" > /dev/tty
	rm -f $lock
fi

echo "$status_string"

exit 0
