#!/bin/bash
# Pre sendmail hook, just do attachment check now

# Set MTA
SENDMAIL=/usr/local/bin/msmtp

# Save msg in file for multiple tests
TMPFILE=`mktemp -t pre-sendmail.XXXXXXXX` || exit 2

# Define test for multipart message
multipart() {
	grep -q '^Content-Type: multipart' "$TMPFILE"
}

# Header to override this check
override() {
	grep -i -q '^X-attached: none$' "$TMPFILE"
}

# Define test for keyword search
attach() {
	grep -a -v '^>' "$TMPFILE" | grep -E -i -q 'attach|patch|附件'
}

# Query function to pass message
ask() {
	# try to get stdin/stdout/stderr from parent process
	pid=$$
	tty=$(ps -o tty= -p $pid)

	while ! [[ $tty = *t* ]]; do  # at least contain a *t* for pts/tty/etc
		pid=$(ps -o ppid= -p $pid)
		tty=$(ps -o tty= -p $pid)
	done

	TTY=/dev/$tty

	# ps -p $pid |grep nonono
	dialog --defaultno --title "Attachment Missing" \
		--yesno "Do you still want to send it anyway?" 0 0 < $TTY > $TTY

	RETURN_VALUE=$?
	clear < $TTY > $TTY
	return $RETURN_VALUE
}

cat > "$TMPFILE"

if override || multipart || ! attach || ask
then
	$SENDMAIL "$@" < "$TMPFILE"
	EXIT_STATUS=$?
else
	echo "Attachment Missing"
	echo
	echo "Add your attachment, or add a header \"X-attached: none\" to override this check."
	EXIT_STATUS=1
fi

rm -f "$TMPFILE"

exit $EXIT_STATUS
