#!/bin/sh

# Configure your favorite diff program here.
DIFF="vimdiff"

# Configure your favorite diff3/merge program here.
DIFF3="vimdiff"

if [ -z $2 ]
then
    echo ERROR: This script expects to be called by subversion
    exit 1
fi

if [ $2 = "-m" ]
then

    # Subversion provides the paths we need as the ninth, tenth, and eleventh 
    # parameters.
    MINE=${9}
    OLDER=${10}
    YOURS=${11}

    # Call the merge command (change the following line to make sense for
    # your merge program).
    #$DIFF3 --older $OLDER --mine $MINE --yours $YOURS
    $DIFF3 $OLDER $MINE $YOURS

    # After performing the merge, this script needs to print the contents
    # of the merged file to stdout.  Do that in whatever way you see fit.
    cat $MINE

else

    # Subversion provides the paths we need as the sixth and seventh 
    # parameters.
    LEFT=${6}
    RIGHT=${7}

    # Call the diff command (change the following line to make sense for
    # your merge program).
    #$DIFF --left $LEFT --right $RIGHT
    $DIFF $LEFT $RIGHT

fi

# Return an errorcode of 0 if no differences were detected or merge successful
# 1 if some differences were detected or conflicts unresolved.
# Any other errorcode will be treated as fatal.
exit 0
