#!/bin/bash

#port=
#user=
#host=
source .hostinfo &> /dev/null || { echo "Please set the hostinfo."; exit 1; }

name=$(basename "$0")
lock=$(pgrep -xf "ssh -CfNqT -D 1080 ${user}@${host} -p $port")

if [[ "$#" = "1" && "$1" = "on" ]]
then
	if [ -n "$lock" ]
	then
		echo Tunnel is already on.
		exit 1
	else
		ssh -CfNqT -D 1080 ${user}@${host} -p $port
		echo Tunnel is turned on.
	fi
elif [[ "$#" = "1" && "$1" = "off" ]]
then
	if [ -n "$lock" ]
	then
		kill $lock
		echo Tunnel is turned off.
	else
		echo Tunnel is already off.
		exit 1
	fi
else
	echo "Usage: $name on | off"
	exit 1
fi

exit 0
