#!/bin/bash

trash ~/.adobe \
	~/.bash_history \
	~/.cache \
	~/.covers \
	~/.dbus \
	~/.fontconfig \
	~/.gconfd \
	~/.gegl-0.0 \
	~/.gimp-2.6 \
	~/.gmrun_history \
	~/.gnome2 \
	~/.gstreamer-0.10 \
	~/.gvfs \
	~/.java \
	~/.local \
	~/.macromedia \
	~/.pulse \
	~/.qt \
	~/.thumbnails \
	~/.xinput.d \
	~/.esd_auth \
	~/.ICEauthority \
	~/.htoprc \
	~/.lesshst \
	~/.libreoffice \
	~/.openoffice.org \
	~/.pulse-cookie \
	~/.recently-used \
	~/.recently-used.xbel \
	~/.viminfo \
	~/.vimperator \
	~/.w3m \
	2>/dev/null

exit 0
